{"name": "Не удается залогиниться в систему", "status": "passed", "description": "Попытка логина с неправильно введенными или отсутствующими логином или паролем", "parameters": [{"name": "wrong_creds", "value": "{'login': 'qwerty1ytrewq', 'password': 'WRONG'}"}, {"name": "status_code", "value": "404"}], "start": 1739452728206, "stop": 1739452728536, "uuid": "df3e3c73-ca06-4acd-9e7b-50777f1c7cdf", "historyId": "e1c911cc4dd532fbad9fe7b915c6e5e2", "testCaseId": "01ceaaa13868027d2f21fb2961bdf35d", "fullName": "tests.test_courier_login.TestCourierLogin#test_courier_wrong_password_or_login_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "GrayCat"}, {"name": "thread", "value": "3508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}